name: Mirror to fr1 branch

on:
  push:
    branches:
      - main

jobs:
  mirror-main-to-fr1:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Push changes to fr1
        run: |
          git pull
          git push origin main:18.0-fr1
